# Generated by Django 4.0.1 on 2023-09-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('IdModule', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=50)),
                ('montant', models.FloatField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='module_photo')),
                ('addDayDateAjout', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
