# Generated by Django 4.0.1 on 2023-09-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('IdCategorie', models.AutoField(primary_key=True, serialize=False)),
                ('categorie', models.CharField(max_length=50)),
                ('addDayCategorie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='categorie',
            field=models.IntegerField(null=True),
        ),
    ]
