# Generated by Django 4.0.1 on 2023-09-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningApp', '0002_categorie_module_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
