# Generated by Django 4.0.1 on 2023-09-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningApp', '0003_categorie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='detailcours',
            field=models.TextField(null=True),
        ),
    ]
