# Generated by Django 4.0.1 on 2023-09-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningApp', '0004_module_detailcours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenus',
            fields=[
                ('IdContenu', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=50)),
                ('video', models.CharField(max_length=50)),
                ('module', models.IntegerField(null=True)),
                ('addDayContenu', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
