# Generated by Django 4.0.1 on 2023-09-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningApp', '0006_contenus_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('IdInscription', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=50)),
                ('codemodule', models.IntegerField()),
                ('niveau', models.CharField(max_length=50)),
                ('montant', models.FloatField()),
                ('etatpaiement', models.BooleanField(default=0)),
                ('etatcours', models.IntegerField()),
                ('user', models.IntegerField()),
            ],
        ),
    ]
